<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-04T20:44:11 IST" name="Suite" finished-at="2025-01-04T20:45:01 IST" duration-ms="49765">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.LoginErrorValidation()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" name="LoginErrorValidation" class="framework.Tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrderTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" name="submitOrderTest" class="framework.Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-01-04T20:44:11 IST" name="SubmitOrderTest" finished-at="2025-01-04T20:44:45 IST" duration-ms="34008">
      <class name="framework.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:11 IST" name="launchApplication" finished-at="2025-01-04T20:44:16 IST" duration-ms="4810" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:16 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-01-04T20:44:37 IST" duration-ms="21280" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[anshika@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Iamking@000]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ZARA COAT 3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at framework.Tests.SubmitOrderTest.submitOrderTest(SubmitOrderTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:37 IST" name="tearDown" finished-at="2025-01-04T20:44:37 IST" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:37 IST" name="launchApplication" finished-at="2025-01-04T20:44:41 IST" duration-ms="3986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrderTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:41 IST" name="submitOrderTest" data-provider="getData" finished-at="2025-01-04T20:44:45 IST" duration-ms="3556" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[prasadaraopuppala@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Target@2024]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[QWERTY]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrderTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:45 IST" name="tearDown" finished-at="2025-01-04T20:44:45 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:framework.Tests.SubmitOrderTest@2ad48653]" started-at="2025-01-04T20:44:45 IST" name="OrderHistoryTest" finished-at="2025-01-04T20:44:45 IST" depends-on-methods="framework.Tests.SubmitOrderTest.submitOrderTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method framework.Tests.SubmitOrderTest.OrderHistoryTest() on instance framework.Tests.SubmitOrderTest@2ad48653 depends on not successfully finished methods 
[framework.Tests.SubmitOrderTest.submitOrderTest() on instance framework.Tests.SubmitOrderTest@2ad48653]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method framework.Tests.SubmitOrderTest.OrderHistoryTest() on instance framework.Tests.SubmitOrderTest@2ad48653 depends on not successfully finished methods 
[framework.Tests.SubmitOrderTest.submitOrderTest() on instance framework.Tests.SubmitOrderTest@2ad48653]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- framework.Tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2025-01-04T20:44:45 IST" name="ErrorValidationTest" finished-at="2025-01-04T20:45:01 IST" duration-ms="15331">
      <class name="framework.Tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:44:45 IST" name="launchApplication" finished-at="2025-01-04T20:44:52 IST" duration-ms="6508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:44:52 IST" name="LoginErrorValidation" finished-at="2025-01-04T20:44:52 IST" duration-ms="450" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password..]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password..]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at framework.Tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:44:53 IST" name="tearDown" finished-at="2025-01-04T20:44:53 IST" duration-ms="58" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:44:53 IST" name="launchApplication" finished-at="2025-01-04T20:45:00 IST" duration-ms="7026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:45:00 IST" name="ProductErrorValidation" finished-at="2025-01-04T20:45:01 IST" duration-ms="957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:framework.Tests.ErrorValidationTest@4d6025c5]" started-at="2025-01-04T20:45:01 IST" name="tearDown" finished-at="2025-01-04T20:45:01 IST" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- framework.Tests.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
